# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata

ROOT = Path(SPECPATH).parent
SRC = ROOT / "src"
WEB = SRC / "omnivert" / "web"
ICON = ROOT / "packaging" / "omnivert.ico"  # exe/window/taskbar icon


def _read_app_version():
    """Pull __version__ from the single source of truth (app_version.py)."""
    import re

    try:
        text = (SRC / "omnivert" / "app_version.py").read_text(encoding="utf-8")
        m = re.search(r'__version__ = "([^"]+)"', text)
        if m:
            return m.group(1)
    except Exception:
        pass
    return "0.0.0"


def _version_tuple(v):
    parts = [int(p) for p in v.split(".") if p.isdigit()][:4]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts)


def build_version_file():
    """Write a Windows VERSIONINFO resource for the EXE.

    Without this, Windows labels the binary the generic "Windows Application" and is more
    prone to serving a stale cached icon across in-place updates. Embedding a real, per-
    release FileVersion/ProductVersion gives the shell a reason to re-read the icon and
    shows the proper product name everywhere (taskbar, Task Manager, file properties).
    """
    app_version = _read_app_version()
    vt = _version_tuple(app_version)
    content = f"""# Auto-generated by packaging/app.spec — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Omnivert'),
        StringStruct('FileDescription', 'Omnivert - Convert anything to Markdown'),
        StringStruct('FileVersion', '{app_version}'),
        StringStruct('InternalName', 'Omnivert'),
        StringStruct('LegalCopyright', 'Copyright 2026 BrandonDry. Licensed under Apache-2.0.'),
        StringStruct('OriginalFilename', 'Omnivert.exe'),
        StringStruct('ProductName', 'Omnivert'),
        StringStruct('ProductVersion', '{app_version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    out_dir = ROOT / "build"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "omnivert_version_info.txt"
    path.write_text(content, encoding="utf-8")
    return path


VERSION_FILE = build_version_file()


def safe_collect_data_files(package):
    try:
        return collect_data_files(package)
    except Exception:
        return []


def safe_collect_submodules(package):
    try:
        return collect_submodules(package)
    except Exception:
        return []


datas = []
if WEB.exists():
    datas.append((str(WEB), "web"))

# Ship license + attribution notices alongside the frozen app.
for notice in ("LICENSE", "NOTICE", "THIRD_PARTY_NOTICES.md"):
    notice_path = ROOT / notice
    if notice_path.exists():
        datas.append((str(notice_path), "."))

for package in (
    "markitdown",
    "magika",
    "onnxruntime",
    "pdfminer",
    "pdfplumber",
    "mammoth",
):
    datas += safe_collect_data_files(package)


def safe_copy_metadata(package, recursive=False):
    try:
        return copy_metadata(package, recursive=recursive)
    except Exception:
        return []


# Bundle package metadata so importlib.metadata.version(...) works in the frozen app
# (drives the Capabilities dialog engine/dependency versions). Recursive picks up the
# engine's dependencies too.
datas += safe_copy_metadata("markitdown", recursive=True)

# Explicit metadata for the optional deps surfaced in the Capabilities dialog
# (these are markitdown extras, not followed by the recursive pass above). Keep in sync
# with _OPTIONAL_DEPS in src/omnivert/capabilities.py.
for dist_name in (
    "pdfminer.six",
    "pdfplumber",
    "mammoth",
    "python-pptx",
    "openpyxl",
    "xlrd",
    "magika",
    "Pillow",
    "pydub",
    "SpeechRecognition",
    "azure-ai-documentintelligence",
    "azure-ai-contentunderstanding",
    "openai",
    "youtube-transcript-api",
):
    datas += safe_copy_metadata(dist_name)

hiddenimports = []
for package in (
    "markitdown",
    "uvicorn",
    "webview",
    "magika",
    "onnxruntime",
):
    hiddenimports += safe_collect_submodules(package)

a = Analysis(
    [str(ROOT / "packaging" / "freeze_entry.py")],
    pathex=[str(SRC)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Omnivert",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon=str(ICON) if ICON.exists() else None,
    version=str(VERSION_FILE),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Omnivert",
)

